import "./css/style.css";
import 'swiper/css/bundle';
import { customSelect } from "./js/customSelect";
import { initProjectsSlider } from "./js/projectsSlider";
import { initWindowHeight } from "./js/windowHeight";
import { initBurgerMenu } from "./js/burgerMenu";
import { initFaq } from "./js/faq";
import { initReviews } from "./js/reviews";
import { initModals } from "./js/initModals";
import { initMap } from './js/map';
import { initAdvantagesSlider } from './js/advantagesSlider';
import { initGlobe } from './js/globe';
import { initQuiz } from "./js/quiz";
import { initForms } from "./js/forms";
import { initTextEffect } from "./js/textEffect";
import { initImageEffect } from "./js/imageEffect";
import { initFoundersSlider } from "./js/foundersSlider";
import { initContacts } from "./js/contacts";
import { initFirstScreenSlider } from "./js/firstScreenSlider";
import { initApartmentsModal } from "./js/apartmentsModal";
import { initMouseScroll } from "./js/mouseScroll";
import { initNews } from './js/news';
import { initPolicyScroll } from "./js/policyScroll";
// import { initPreloader } from "./js/preloader";

document.addEventListener("DOMContentLoaded", function () {
    customSelect();
    initProjectsSlider();
    initWindowHeight();
    initBurgerMenu();
    initFaq();
    initReviews();
    initModals();
    initAdvantagesSlider()
    initMap();
    initGlobe();
    initQuiz();
    initForms();
    initTextEffect();
    initImageEffect();
    initFoundersSlider();
    initContacts();
    initFirstScreenSlider();
    initApartmentsModal();
    initMouseScroll();
    initNews();
    initPolicyScroll();
    // initPreloader();
});
